apiVersion: v2
name: reservoir-jit
description: A service that provides a clustering storage of metadata for Data Integration purposes
type: application

# Use semver, note that this is replaced by the publish action
version: 0.1.0

# appVersion is used as the Docker image tag by the chart
appVersion: "master"

dependencies:
  - name: okapi-hooks
    repository: oci://ghcr.io/indexdata/charts
    version: ">0.1.0-0"
    condition: okapi-hooks.enabled
