openapi: 3.0.0
info:
  title: Reservoir SRU API
  version: v1
paths:
  /reservoir/sru:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
      - $ref: parameters/query.yaml
      - $ref: parameters/start-record.yaml
      - $ref: parameters/maximum-records.yaml
      - $ref: parameters/sru-version.yaml
      - $ref: parameters/sru-operation.yaml
      - $ref: parameters/sru-record-schema.yaml
    get:
      description: SRU service
      operationId: sruService
      responses:
        "200":
          description: SRU response
          content:
            text/xml:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
components:
  responses:
    trait_400:
      description: Bad request
      content:
        text/plain:
          schema:
            type: string
            example: Invalid JSON in request
        application/json:
          schema:
            type: object
            example: { "error": "Invalid JSON in request" }
    trait_500:
      description: Internal error
      content:
        text/plain:
          schema:
            type: string
            example: Internal server error, contact administrator
