# Stage 1: The builder stage with JDK and Maven
FROM container-registry.oracle.com/graalvm/jdk:24 AS builder
RUN microdnf install -y maven

WORKDIR /app

# Needed for git-commit-id-plugin
COPY .git/ .git

# Copy all source files needed for the build
COPY pom.xml .
COPY checkstyle/ checkstyle
COPY client/ client
COPY descriptors/ descriptors
COPY js/ js
COPY server/ server
COPY util/ util
COPY xsl/ xsl

# Build the application, creating the fat JAR
RUN mvn -B -DskipTests package

# Stage 2: The final, smaller runtime image
FROM container-registry.oracle.com/graalvm/jre:24

WORKDIR /app

# Create a non-root user for security
RUN useradd \
  --home-dir /nonexistent \
  --shell /sbin/nologin \
  --no-create-home \
  --uid 65532 \
  myuser

# Copy only the application JAR from the builder stage
COPY --from=builder /app/server/target/mod-reservoir-server-fat.jar .

# Switch to the non-root user
USER myuser

EXPOSE 8081

# Set the command to run the application
CMD ["/usr/lib64/graalvm/graalvm-java24/bin/java", "$JAVA_OPTS", "--sun-misc-unsafe-memory-access=allow", "--enable-native-access=ALL-UNNAMED", "-jar", "mod-reservoir-server-fat.jar"]
