FROM container-registry.oracle.com/graalvm/native-image:24 AS build
# Red Hat Enterprise Linux release 10.0 (CentOS Stream)
RUN microdnf install -y maven

WORKDIR /app

# create runtime user
RUN useradd \
  --home-dir /nonexistent \
  --shell /sbin/nologin \
  --uid 65532 \
  --no-create-home \
  reservoir

# Needed for git-commit-id-plugin
COPY .git/ .git

# Reamining files are copied for building the native image
COPY pom.xml .
COPY checkstyle/ checkstyle
COPY client/ client
COPY descriptors/ descriptors
COPY js/ js
COPY server/ server
COPY util/ util
COPY xsl/ xsl

# Run native image build
RUN --mount=type=cache,sharing=shared,target=/root/.m2/repository mvn -B -DskipTests -Pnative package

# Save list of shared lib deps
RUN ldd server/target/reservoir-native | tr -s '[:blank:]' '\n' | grep '^/' | \
  xargs -I % sh -c 'mkdir -p $(dirname deps%); cp % deps%;'

RUN mkdir -p /app/tmp/vertx-cache
RUN chown -R reservoir:reservoir /app/tmp

FROM scratch

# user, group, and timezone data
COPY --from=build /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=build /etc/passwd /etc/passwd
COPY --from=build /etc/group /etc/group

COPY --from=build --chown=reservoir:reservoir /app/tmp /tmp
COPY --from=build /app/server/target/reservoir-native /reservoir-native
COPY --from=build /app/client/target/client-native /client-native
COPY --from=build /app/deps /

USER reservoir:reservoir

ENV JAVA_OPTS=""
ENV HTTP_PORT=8081
EXPOSE $HTTP_PORT

ENTRYPOINT ["sh", "-c", "/reservoir-native -Dport=$HTTP_PORT $JAVA_OPTS \"$@\"", "reservoir-native"]
CMD []
