name: publish-image

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - mvn-verify
    types:
      - completed
    branches:
      - master
      - RSRVR-12-jit-native-image

env:
  REGISTRY: ghcr.io
  CURRENT_BRANCH: ${{ github.ref_name }}

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - module: jit
            dockerfile: ./Dockerfile-jit
            image: ${{ github.repository }}-jit
          - module: native
            dockerfile: ./Dockerfile-native
            image: ${{ github.repository }}-native

    steps:
      - name: checkout module
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file:  ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
