name: publish-image

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - mvn-verify
    types:
      - completed
    branches:
      - master

env:
  REGISTRY: ghcr.io
  CURRENT_BRANCH: ${{ github.ref_name }}

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - module: jit
            dockerfile: ./Dockerfile-jit
            image: ${{ github.repository }}-jit
          # native build is extremely slow in CI (20m), only enable if the chart uses the  native image
          # - module: native
          #   dockerfile: ./Dockerfile-native
          #   image: ${{ github.repository }}-native

    steps:
      - name: checkout module
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up GraalVM to restore Maven repository cache
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'
          distribution: 'graalvm'
          cache: 'maven'

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file:  ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_COMMIT=${{ github.sha }}
            MAVEN_MOUNT_TYPE=bind
            MAVEN_MOUNT_SOURCE=${{ env.HOME }}/.m2/repository
          cache-from: type=gha
          cache-to: type=gha,mode=max
