name: GraalVM build
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1 # https://graalvm.github.io/native-build-tools/latest/maven-plugin.html
        with:
          java-version: '24.0.2'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create native package
        run: mvn -DskipTests -B -Pnative package
